# Generated by Django 4.2.28 on 2026-02-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_extra_patient_fields'),
        ('management', '0002_new_profile_fields'),
    ]

    operations = [
    ]
