# Generated by Django 4.2.28 on 2026-03-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='records.patientvisit'),
        ),
    ]
