# Generated by Django 4.2.28 on 2026-03-09 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid — Awaiting Nurse'), ('vitals', 'Nurse Taking Vitals'), ('with_doctor', 'With Doctor'), ('lab_pending', 'Awaiting Lab Payment'), ('lab_paid', 'Lab Paid — Processing'), ('lab_processing', 'Lab In Progress'), ('rx_pending', 'Awaiting Prescription Payment'), ('rx_paid', 'Prescription Paid — At Pharmacy'), ('pharmacy', 'At Pharmacy'), ('completed', 'Completed')], default='pending_payment', max_length=30)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chief_complaint', models.TextField(blank=True)),
                ('visit_summary', models.TextField(blank=True)),
                ('queue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation_paid_at', models.DateTimeField(blank=True, null=True)),
                ('nurse_history_deleted', models.BooleanField(default=False)),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_visits', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('receptionist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft — Awaiting Patient Review'), ('patient_reviewed', 'Patient Reviewed — Awaiting Payment'), ('pending', 'Pending — Awaiting Surgery'), ('underway', 'Underway'), ('ended', 'Ended'), ('paid', 'Paid — Scheduled'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('procedure_name', models.CharField(max_length=300)),
                ('purpose_and_benefits', models.TextField(blank=True)),
                ('known_risks', models.TextField(blank=True)),
                ('alternative_treatments', models.TextField(blank=True)),
                ('anesthesia_type', models.CharField(blank=True, max_length=100)),
                ('additional_procedures_auth', models.BooleanField(default=False)),
                ('tissue_disposal_auth', models.BooleanField(default=False)),
                ('residents_involved', models.BooleanField(default=False)),
                ('observers_permitted', models.BooleanField(default=False)),
                ('photography_permitted', models.BooleanField(default=False)),
                ('blood_transfusion_consent', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], default='na', max_length=10)),
                ('financial_disclosure', models.TextField(blank=True)),
                ('advance_directives', models.TextField(blank=True)),
                ('postop_instructions', models.TextField(blank=True)),
                ('patient_acknowledged', models.BooleanField(default=False)),
                ('witness_name', models.CharField(blank=True, max_length=100)),
                ('surgery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surgery_fee_parts', models.PositiveIntegerField(default=1)),
                ('surgery_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surgery_drug_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surgery_lab_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('patient_full_name_signed', models.CharField(blank=True, max_length=200)),
                ('patient_signed_at', models.DateTimeField(blank=True, null=True)),
                ('patient_questions', models.TextField(blank=True)),
                ('patient_understanding', models.BooleanField(default=False)),
                ('patient_voluntary', models.BooleanField(default=False)),
                ('admit_after_surgery', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(choices=[('general_male', 'General Male Ward'), ('general_female', 'General Female Ward'), ('general_children', 'General Children Ward'), ('private', 'Private Ward'), ('semi_private', 'Semi-Private Ward')], max_length=30)),
                ('bed_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid — Pending Admission'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='pending_payment', max_length=20)),
                ('admission_reason', models.TextField(blank=True)),
                ('daily_ward_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_fee_parts', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_payments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_assignments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='records.patientvisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('pulse_rate', models.CharField(blank=True, max_length=20)),
                ('temperature', models.CharField(blank=True, max_length=20)),
                ('respiratory_rate', models.CharField(blank=True, max_length=20)),
                ('oxygen_saturation', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('bmi', models.CharField(blank=True, max_length=20)),
                ('pain_level', models.CharField(blank=True, max_length=5)),
                ('nurse_note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='records.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('price_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_labs', to='records.surgery')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drug')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_drugs', to='records.surgery')),
            ],
        ),
        migrations.AddField(
            model_name='surgery',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_surgery', to='records.wardadmission'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgery',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgery',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='records.patientvisit'),
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_written', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='records.patientvisit')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionPrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_drip', models.BooleanField(default=False)),
                ('is_injection', models.BooleanField(default=False)),
                ('injection_days', models.PositiveIntegerField(blank=True, null=True)),
                ('injection_times_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='records.admissionprescription')),
            ],
        ),
        migrations.AddField(
            model_name='admissionprescription',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='records.wardadmission'),
        ),
        migrations.AddField(
            model_name='admissionprescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
