# Generated by Django 4.2.28 on 2026-03-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid — Awaiting Nurse'), ('vitals', 'Nurse Taking Vitals'), ('with_doctor', 'With Doctor'), ('lab_pending', 'Awaiting Lab Payment'), ('lab_paid', 'Lab Paid — Processing'), ('lab_processing', 'Lab In Progress'), ('rx_pending', 'Awaiting Prescription Payment'), ('rx_paid', 'Prescription Paid — At Pharmacy'), ('pharmacy', 'At Pharmacy'), ('completed', 'Completed'), ('admitted', 'Admitted to Ward')], default='pending_payment', max_length=30),
        ),
    ]
