# Generated by Django 4.2.28 on 2026-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_merge_0002_new_fields_0003_surgery_patient_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctornote',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='doctornote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft — Awaiting Patient Review'), ('patient_reviewed', 'Patient Reviewed — Awaiting Payment'), ('paid', 'Paid — Scheduled'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
