# Generated by Django 4.2.28 on 2026-03-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='original_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
