# Generated by Django 4.2.28 on 2026-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_surgery_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='surgery_payment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab Tests'), ('prescription', 'Prescription / Drugs'), ('admission', 'Ward Admission'), ('surgery', 'Surgery'), ('admission_medication', 'Ward Medication')], max_length=20),
        ),
    ]
